Practice_Mvc/Controllers/IssueController.cs
using Practice_Mvc.Data;
using Practice_Mvc.Domain;
using Practice_Mvc.Filters;
using Practice_Mvc.Models.Issue;
using System;
using Microsoft.Web.Mvc;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using Practice_Mvc.Infrastructure;
using Practice_Mvc.Infrastructure.Alerts;

namespace Practice_Mvc.Controllers
{
    public class IssueController : Controller
    {
		private readonly ApplicationDbContext _context;
		private readonly ICurrentUser _currentUser;

		public IssueController(ApplicationDbContext context,
			ICurrentUser currentUser)
		{
			_context = context;
			_currentUser = currentUser;
		}

		private SelectListItem[] GetAvailableUsers()
		{
			return _context.Users.Select(u => new SelectListItem { Text = u.UserName, Value = u.Id }).ToArray();
		}

		private SelectListItem[] GetAvailableIssueTypes()
		{
			return Enum.GetValues(typeof(IssueType))
				.Cast<IssueType>()
				.Select(t => new SelectListItem { Text = t.ToString(), Value = t.ToString() })
				.ToArray();
		}

		[ChildActionOnly]
		public ActionResult YourIssuesWidget()
		{
			var models = _context.Issues
                .Where(i => i.AssignedTo.Id == _currentUser.User.Id)
                .Project().To<IssueSummaryViewModel>();

			return PartialView(models.ToArray());
		}

		[ChildActionOnly]
		public ActionResult CreatedByYouWidget()
        {
            var models = _context.Issues
                .Where(i => i.Creator.Id == _currentUser.User.Id)
                .Project().To<IssueSummaryViewModel>();
               
			return PartialView(models.ToArray());
		}

		[ChildActionOnly]
		public ActionResult AssignmentStatsWidget()
        {
            var stats = _context.Users.Project().To<AssignmentStatsViewModel>();

			return PartialView(stats.ToArray());
		}

		public ActionResult New()
		{
			var form = new NewIssueForm
			{
				AvailableUsers = GetAvailableUsers(),
				AvailableIssueTypes = GetAvailableIssueTypes()
			};
			return View(form);
		}

		[HttpPost, ValidateAntiForgeryToken, Log("Created issue")]
		public ActionResult New(NewIssueForm form)
		{
			if (!ModelState.IsValid)
			{
				form.AvailableUsers = GetAvailableUsers();
				form.AvailableIssueTypes = GetAvailableIssueTypes();
				return View(form);
			}

			var assignedToUser = _context.Users.Single(u => u.Id == form.AssignedToUserID);

			_context.Issues.Add(new Issue(_currentUser.User, assignedToUser, form.IssueType, form.Subject, form.Body));

			_context.SaveChanges();

			//return RedirectToAction("Index", "Home");
            return this.RedirectToAction<HomeController>(c => c.Index())
                .WithSuccess("Issue created!");
        }

		[Log("Viewed issue {id}")]
		public ActionResult View(int id)
		{
			var model = _context.Issues
                .Project().To<IssueDetailsViewModel>()
				.SingleOrDefault(i => i.IssueID == id);

			if (model == null)
            {
                return this.RedirectToAction<HomeController>(c => c.Index())
                    .WithError("Unable to find this issue. Maybe it was deleted");
            }

			return View(model);
		}

		[Log("Started to edit issue {id}")]
		public ActionResult Edit(int id)
		{
			var model = _context.Issues
                .Project().To<EditIssueForm>()
				.SingleOrDefault(i => i.IssueID == id);

			if (model == null)
			{
                return this.RedirectToAction<HomeController>(c => c.Index())
                    .WithError("Unable to find this issue. Maybe it was deleted");
			}

            model.AvailableUsers = GetAvailableUsers();
            model.AvailableIssueTypes = GetAvailableIssueTypes();

			return View(model);
		}

		[HttpPost, Log("Saving changes")]
		public ActionResult Edit(EditIssueForm form)
		{
			if (!ModelState.IsValid)
			{
				form.AvailableUsers = GetAvailableUsers();
				form.AvailableIssueTypes = GetAvailableIssueTypes();
				return View(form);
			}

			var issue = _context.Issues.SingleOrDefault(i => i.IssueID == form.IssueID);

			if (issue == null)
			{
                return this.RedirectToAction<HomeController>(c => c.Index())
                    .WithError("Unable to find this issue. Maybe it was deleted");
			}

			var assignedToUser = _context.Users.Single(u => u.Id == form.AssignedToId);

			issue.Subject = form.Subject;
			issue.AssignedTo = assignedToUser;
			issue.Body = form.Body;
			issue.IssueType = form.IssueType;


			//return RedirectToAction("View", new { id = form.IssueID });
            return this.RedirectToAction(c => c.View(form.IssueID))
                .WithSuccess("Changes saved!");
        }

		[HttpPost, ValidateAntiForgeryToken, Log("Deleted issue {id}")]
		public ActionResult Delete(int id)
		{
			var issue = _context.Issues.Find(id);

			if (issue == null)
			{
                return this.RedirectToAction<HomeController>(c => c.Index())
                    .WithError("Unable to find this issue. Maybe it was deleted");
			}

			_context.Issues.Remove(issue);

			_context.SaveChanges();

			//return RedirectToAction("Index", "Home");
            return this.RedirectToAction<HomeController>(c => c.Index())
                .WithSuccess("Issue deleted!");
        }
	}
}

Practice_Mvc/Views/Shared/_Alerts.cshtml
@using Practice_Mvc.Infrastructure.Alerts
@if (TempData.GetAlerts().Any())
{
    <div class="container alert-container">
        @foreach (var alert in TempData.GetAlerts())
        {
            <div class="alert @alert.AlertClass alert-dismissable">
                <button type="button" class="close" data-dismiss="alert"
                        aria-hidden="true">
                    &times;
                </button>
                @alert.Message
            </div>
        }
    </div>
}

Practice_Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Practice MVC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Practice MV", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("New Issue", "New", "Issue")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
<div class="container body-content">
    @Html.Partial("_Alerts")
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>